# Postgresql

development:
  adapter: postgresql
  encoding: unicode
  database: glaring_dev
  username: development
  password: development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: glaring_test
  username: development
  password: development

  pool: 5
